### PR TITLE
added search using regex by name and skills

### PR DESCRIPTION
**Pull request by megabyte98**
issue handle #42 

file affected :
app/controllers/search.js
app/routes/search.js
server.js

### CODE REVIEW

**Comment by Aditya-Dawadikar** [comment]
@megabyte98 chan you share the test screen shots

**Comment by megabyte98** [comment]
The response on route  (http://localhost:3000/api/search/name?name=te) is as follows :
[
    {
        "personal": {
            "name": "Test User 001",
            "college": "PCCOE",
            "department": "Computer ",
            "year": "TE",
            "division": "B",
            "rollno": "101"
        },
        "social": {
            "phone": 1001001009,
            "linkedin": "https://in.linkedin.com/",
            "github": "https://github.com/adityamahajan-io",
            "personalwebsite": "https://www.google.com/",
            "resume": "https://www.google.com/",
            "iswhatsapp": true
        },
        "skills": {
            "skill": [
                "Java"
            ],
            "projectsforskills": [
                "https://www.google.com/"
            ],
            "primaryskill": "Data Science",
            "secondaryskill": "Web Development",
            "cgpa": 9.2
        },
        "optionals": {
            "languages_known": [
                "English",
                "Marathi",
                "Hindi"
            ],
            "introduction": "Student",
            "gender": "Male",
            "age": 19,
            "mother_tongue": "Marathi",
            "pronoun": "he/him"
        },
        "metaData": {
            "hasAdminAccess": false,
            "github_metadata_object": {
                "login": "adityamahajan-io",
                "id": 66865722,
                "node_id": "MDQ6VXNlcjY2ODY1NzIy",
                "avatar_url": "https://avatars0.githubusercontent.com/u/66865722?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/adityamahajan-io",
                "html_url": "https://github.com/adityamahajan-io",
                "followers_url": "https://api.github.com/users/adityamahajan-io/followers",
                "following_url": "https://api.github.com/users/adityamahajan-io/following{/other_user}",
                "gists_url": "https://api.github.com/users/adityamahajan-io/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/adityamahajan-io/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/adityamahajan-io/subscriptions",
                "organizations_url": "https://api.github.com/users/adityamahajan-io/orgs",
                "repos_url": "https://api.github.com/users/adityamahajan-io/repos",
                "events_url": "https://api.github.com/users/adityamahajan-io/events{/privacy}",
                "received_events_url": "https://api.github.com/users/adityamahajan-io/received_events",
                "type": "User",
                "site_admin": false,
                "name": "Aditya Mahajan",
                "company": null,
                "blog": "",
                "location": null,
                "email": null,
                "hireable": null,
                "bio": "\r\nML Engg at SoftTech Data Securities \r\n| MERN Stack Developer |\r\nCurrently working on Deep Learning for Autonomous Robots\r\n",
                "twitter_username": null,
                "public_repos": 3,
                "public_gists": 0,
                "followers": 4,
                "following": 4,
                "created_at": "2020-06-13T08:23:20Z",
                "updated_at": "2020-10-02T14:00:39Z"
            }
        },
        "_id": "5f77a6b7d11499002435094f",
        "email": "testuser001@gmail.com",
        "password": "$2b$10$60gWavkhV6AutWBnBZE6BOivZQKMjg4jKD1ALdL6Ik624GZYBk2Wu",
        "rating": 2,
        "created_at": "2020-10-02T22:17:44.541Z",
        "updated_at": "2020-10-02T22:17:44.541Z",
        "__v": 0
    },
    {
        "personal": {
            "name": "Tejas Morkar",
            "college": "PCCOE",
            "department": "Computer",
            "year": "TE",
            "division": "B",
            "rollno": "104"
        },
        "social": {
            "phone": 1170002009,
            "linkedin": "https://in.linkedin.com/",
            "github": "https://github.com/adityamahajan-io",
            "personalwebsite": "https://www.google.com/",
            "resume": "https://www.google.com/",
            "iswhatsapp": true
        },
        "skills": {
            "skill": [
                "Full Stack Developement"
            ],
            "projectsforskills": [
                "https://www.google.com/"
            ],
            "primaryskill": "Data Science",
            "secondaryskill": "Cloud",
            "cgpa": 9
        },
        "optionals": {
            "languages_known": [
                "English",
                "Marathi"
            ],
            "introduction": "Student",
            "gender": "Male",
            "age": 20,
            "mother_tongue": "Marathi",
            "pronoun": "he/him"
        },
        "metaData": {
            "hasAdminAccess": false,
            "github_metadata_object": {
                "login": "adityamahajan-io",
                "id": 66865722,
                "node_id": "MDQ6VXNlcjY2ODY1NzIy",
                "avatar_url": "https://avatars0.githubusercontent.com/u/66865722?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/adityamahajan-io",
                "html_url": "https://github.com/adityamahajan-io",
                "followers_url": "https://api.github.com/users/adityamahajan-io/followers",
                "following_url": "https://api.github.com/users/adityamahajan-io/following{/other_user}",
                "gists_url": "https://api.github.com/users/adityamahajan-io/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/adityamahajan-io/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/adityamahajan-io/subscriptions",
                "organizations_url": "https://api.github.com/users/adityamahajan-io/orgs",
                "repos_url": "https://api.github.com/users/adityamahajan-io/repos",
                "events_url": "https://api.github.com/users/adityamahajan-io/events{/privacy}",
                "received_events_url": "https://api.github.com/users/adityamahajan-io/received_events",
                "type": "User",
                "site_admin": false,
                "name": "Aditya Mahajan",
                "company": null,
                "blog": "",
                "location": null,
                "email": null,
                "hireable": null,
                "bio": "\r\nML Engg at SoftTech Data Securities \r\n| MERN Stack Developer |\r\nCurrently working on Deep Learning for Autonomous Robots\r\n",
                "twitter_username": null,
                "public_repos": 3,
                "public_gists": 0,
                "followers": 4,
                "following": 4,
                "created_at": "2020-06-13T08:23:20Z",
                "updated_at": "2020-10-02T14:00:39Z"
            }
        },
        "_id": "5f781b6ae1154200249e5ee3",
        "email": "tejas@gmail.com",
        "password": "$2b$10$Zc9FFUfTy43b/3vVSag5UuOu8mR4FYORE3Rfi3ZjZFCS8rAwEG/3e",
        "rating": 3,
        "created_at": "2020-10-03T06:39:40.458Z",
        "updated_at": "2020-10-03T06:39:40.458Z",
        "__v": 0
    }
]

image

**Comment by megabyte98** [comment]
same is for the route (http://localhost:3000/api/search/skills?skill=nodejs) is as follows : 

[
    {
        "personal": {
            "name": "Geek Dev",
            "college": "PCCOE",
            "department": "COMP",
            "year": "TE",
            "division": "C",
            "rollno": "TECOC311"
        },
        "social": {
            "phone": 9900776655,
            "linkedin": "https://www.linkedin.com/in/",
            "github": "https://github.com/tejas",
            "personalwebsite": "https://tejasmorkar.tech/",
            "resume": "https://tejasmorkar.tech/",
            "iswhatsapp": true
        },
        "skills": {
            "skill": [
                "Nodejs",
                "Angular"
            ],
            "projectsforskills": [
                "https://www.linkedin.com/in/",
                "https://www.linkedin.com/in/",
                "https://www.linkedin.com/in/"
            ],
            "primaryskill": "Nodejs",
            "secondaryskill": "Angular",
            "cgpa": 9
        },
        "optionals": {
            "languages_known": [
                "Hindi",
                "English"
            ],
            "introduction": "Hello",
            "gender": "Male",
            "age": 20,
            "mother_tongue": "Marathi",
            "pronoun": "he/him"
        },
        "metaData": {
            "hasAdminAccess": true,
            "github_metadata_object": {
                "login": "aditya",
                "id": 45139041,
                "node_id": "MDQ6VXNlcjQ1MTM5MDQx",
                "avatar_url": "https://avatars3.githubusercontent.com/u/45139041?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/bhavansh",
                "html_url": "https://github.com/bhavansh",
                "followers_url": "https://api.github.com/users/bhavansh/followers",
                "following_url": "https://api.github.com/users/bhavansh/following{/other_user}",
                "gists_url": "https://api.github.com/users/bhavansh/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/bhavansh/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/bhavansh/subscriptions",
                "organizations_url": "https://api.github.com/users/bhavansh/orgs",
                "repos_url": "https://api.github.com/users/bhavansh/repos",
                "events_url": "https://api.github.com/users/bhavansh/events{/privacy}",
                "received_events_url": "https://api.github.com/users/bhavansh/received_events",
                "type": "User",
                "site_admin": false,
                "name": "Bhavansh Gupta",
                "company": null,
                "blog": "",
                "location": "Pune",
                "email": null,
                "hireable": null,
                "bio": "Student of Computer Engineering at Pimpri Chinchwad College of Engineering.\r\nJust Starting",
                "twitter_username": "bhavanshgupta",
                "public_repos": 20,
                "public_gists": 0,
                "followers": 28,
                "following": 65,
                "created_at": "2018-11-18T08:07:57Z",
                "updated_at": "2020-08-25T15:04:57Z"
            }
        },
        "_id": "5f77efb296e48e1bc401dbd5",
        "email": "testUser110@gmail.com",
        "password": "$2b$10$OHFofIXBCcH4NR/sdrIYcuqu8rJAxGdqqvUAcmu9g3SiWvYqRlewK",
        "rating": 4.5,
        "created_at": "2020-10-03T03:35:10.183Z",
        "updated_at": "2020-10-03T03:35:10.183Z",
        "__v": 0
    }
]

**Review by Aditya-Dawadikar — APPROVED** [review]
Superb work @megabyte98. Your contribution is valuable to us. Keep hacking!!

**Pull request merged**
