### PR TITLE
feat(sort): add student sort endpoint

### LINKED ISSUE #43: Filter API to Filter Students Based on rating
Filter API to Filter Students Based on rating

**Needs Further Discussion**

### PR DESCRIPTION
**Pull request by ruddha2001**
## Features
- Sort students based on `rating` (default).
- Accept *optional* parameters to sort by (prop1, prop2 and prop3).
- Handle any number of parameters from 0 to 3.

## How to use?
- `/sort?prop1=some&prop2=some&prop3=some` - returns Document[].

## Known Issues
- For using URL queries, `prop1` is mandated otherwise other params will not be detected.

## Issues
- Resolve #43 

## Screenshots
image
image

### CODE REVIEW

**Comment by Aditya-Dawadikar** [comment]
@ruddha2001 have you tested the endpoint? can you share the results after testing?

**Comment by ruddha2001** [comment]
@Aditya-Dawadikar Not really for two reasons.
1. There is no unit testing, nor any collection nor any testing credentials. So I cannot generate an auth token in any way.
2. The only alternative is to create my own data (fake randomised account). But the database is not mine. And working on other databases without explicit approval is both tedious and not recommended.

**Comment by Aditya-Dawadikar** [comment]
Im sure we asked you for your email so that we can send you the required credentials

**Comment by ruddha2001** [comment]
@Aditya-Dawadikar The email I was sent dated 02 October 2020 says and I quote,
> EMAIL = use your own
> PASS = use your own

And that for obvious reasons do not work.
I am attaching the Postman screenshot as proof.
image


Without any additional credentials, it is not possible for me to test anything.

**Comment by Aditya-Dawadikar** [comment]
image

try using these for login. require the bearer token from the response body and then add it to the request headers, authorization. for all the endpoints that have student user access. 
This way u will be an authenticated user to request the data. the token expires in 10 hrs.

**Comment by ruddha2001** [comment]
@Aditya-Dawadikar Thank you so much!
I do the stuff required and update this PR.

**Comment by ruddha2001** [comment]
image
@Aditya-Dawadikar Apologies but the credentials are not working aka email is found but passwords do not match

**Comment by Aditya-Dawadikar** [comment]
image

**Comment by ruddha2001** [comment]
@Aditya-Dawadikar I have updated this PR's description.
Let me know if this will suffice as a successful test.

**Comment by Aditya-Dawadikar** [comment]
I checked you PR and changed files. Just share me a screenshot of the successful test with all three cases and I'll merge your code.

**Comment by ruddha2001** [comment]
@Aditya-Dawadikar 
Case 1 - No param (Default case)
image

Case 2 - Only Param 1
image

Case 3 - Param 1 and Param 2
image

Case 4 - Param 1, Param 2 and Param 3
image

**Review by Aditya-Dawadikar — APPROVED** [review]
Congrats on your first successful pull request that is being accepted on our repo. Your contribution is valuable to us. Keep hacking!!

**Pull request merged**
